# Note
<font color=red>

**Respected LU Team,**

**Please reconsider this question as in previous submission I forgot to remove repeated indices.**

**Thank You**

**11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [11]:
import numpy as np 
Z = np.random.randn(10,1)#creates a random vector of given order
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)#generates 4 random integers in a specified range,used as index values
print("The Index values obtained are:")
print(I)
J=np.unique(I,axis=0)#removes the duplicate values
print("The final unique index values are:")
print(J)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,J,1)#Adds 1 to the elements in given vector (Z) at the specified index values(I)
print(Z)

The original vector is:
[[-1.58985892e+00]
 [-6.48583588e-01]
 [ 2.69989102e-03]
 [-2.84029191e-01]
 [ 3.72357271e+00]
 [-4.23549329e-01]
 [ 1.87796258e+00]
 [ 4.17865694e-01]
 [ 1.05720174e-01]
 [ 1.05364936e+00]]
The Index values obtained are:
[6 0 2 0]
The final unique index values are:
[0 2 6]
Final vector after adding 1 to corresponding elements at the specified indices:
[[-0.58985892]
 [-0.64858359]
 [ 1.00269989]
 [-0.28402919]
 [ 3.72357271]
 [-0.42354933]
 [ 2.87796258]
 [ 0.41786569]
 [ 0.10572017]
 [ 1.05364936]]
